### ISSUE TITLE
remove post formats by default

### ISSUE THREAD

**Issue by norcross** [liquidweb/sticky-tax#12]
the vast majority of people don't use them, and of those that do, most don't use them in a traditional taxonomy way. so I'm proposing we add a filter to remove them in the `get_taxonomies_for_object` function.

Example:

```
// Check the filter for excluding post formats.
$exclude    = apply_filters( 'stickytax_exclude_post_formats', true );

if ( ! empty( $exclude ) ) {
	unset( $taxonomies['post_format'] );
}
```

**Comment by stevegrunwell** [comment]
![Captain Picard ordering "Make it so"](http://s2.quickmeme.com/img/62/628b747f8ccdfb757062f36a27eedecfc2295f515c0586e05fbfb0620c0571a2.jpg)
