### ISSUE TITLE
Code review plugin

### ISSUE THREAD

**Issue by stevegrunwell** [liquidweb/sticky-tax#6]
@norcross As mentioned on the call earlier, I'd appreciate a code review on the plugin before I push the first release to WordPress.org. We received approval on the plugin over the weekend, but you have a great habit of catching some BS, and I'd rather we see that now rather than after it's live.

**Comment by norcross** [comment]
Initial thoughts:

- the meta box title is too short
- the functions getting the taxonomies and post types should be abstracted so they can be used in other places
- for `append_sticky_class`, is there a default WP class that get applied to regular sticky posts that we should use also?
- is `pre_get_posts` not being used for a specific reason?
- meta is storing multiple keys as opposed to a single serialized array. reasoning?

**Comment by stevegrunwell** [comment]
> the meta box title is too short

Added #9 to address.

> the functions getting the taxonomies and post types should be abstracted so they can be used in other places

Note added to #3

> for append_sticky_class, is there a default WP class that get applied to regular sticky posts that we should use also?

Yup, `.sticky`; added #10 to address.

> is pre_get_posts not being used for a specific reason?

This is the mistake that many "sticky in a category"-type plugins make: they attempt to introduce additional meta queries or shift posts around after they're retrieved, often leading to off-by-one errors, stickies appearing on multiple pages of results, or otherwise complicating the query. This leverages a small, simple, and heavily-cached secondary query to let MySQL do the ordering, instead.

> meta is storing multiple keys as opposed to a single serialized array. reasoning?

For the sake of the query in `get_sticky_posts_for_term()`, which finds posts based on those that have the given term ID; using multiple rows enables us to avoid MySQL `LIKE` hacks to avoid, for instance, capturing posts sticky in term ID `22` when we're looking for those in `2`.

**Comment by norcross** [comment]
valid responses are valid

**Comment by norcross** [comment]
I believe this has been accomplished

**Comment by stevegrunwell** [comment]
Agreed. Collaboration FTW!
