### ISSUE TITLE
Rename meta box

### ISSUE THREAD

**Issue by stevegrunwell** [liquidweb/sticky-tax#9]
As pointed out in #6, the title of "Sticky" for the meta box is kinda weak. Surely there's something better.

![Current "Sticky" meta box on the post edit screen](https://user-images.githubusercontent.com/233836/29589852-020f4ad8-8765-11e7-978f-b119a3b65f5a.png)

**Comment by lukecav** [comment]
What about **Make Sticky**?

![make sticky](https://user-images.githubusercontent.com/5797332/29684705-2dfab6e8-88d0-11e7-9e8b-a87e3827de9b.png)
